services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: bkn1_postgres
    environment:
      POSTGRES_DB: bkn1_db
      POSTGRES_USER: bkn1_user
      POSTGRES_PASSWORD: bkn1_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - bkn1_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bkn1_user -d bkn1_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # PgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: bkn1_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - bkn1_network
    depends_on:
      - postgres

  # Flask API Backend
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bkn1_api
    environment:
      DATABASE_URL: postgresql://bkn1_user:bkn1_password@postgres:5432/bkn1_db
      SECRET_KEY: d2faf048fdd50310e08f393074652b444ca68160e355008e95cd674026fd85a4
      FLASK_ENV: development
    volumes:
      - ./backend:/app
      - ./uploads:/app/uploads
    ports:
      - "5000:5000"
    networks:
      - bkn1_network
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Vue.js Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: bkn1_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    networks:
      - bkn1_network
    environment:
      - NODE_ENV=development

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: bkn1_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./uploads:/var/www/uploads
    ports:
      - "80:80"
    networks:
      - bkn1_network
    depends_on:
      - frontend
      - api

  # Metabase for BI Dashboard
  metabase:
    image: metabase/metabase:latest
    container_name: bkn1_metabase
    ports:
      - "3001:3000"
    networks:
      - bkn1_network
    volumes:
      - ./metabase_data:/metabase.db
      - ./metabase-entrypoint.sh:/entrypoint.sh
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

volumes:
  postgres_data:
  pgadmin_data:
  metabase_data:

networks:
  bkn1_network:
    driver: bridge
